/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#002147",
        "on-primary-container": "#708ab5",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1b1e",
        "on-surface-variant": "#44474e",
        "on-tertiary-fixed": "#191c1d",
        "tertiary": "#090b0c",
        "surface-container-highest": "#e3e2e6",
        "outline-variant": "#c4c6cf",
        "primary": "#000a1e",
        "on-secondary-fixed": "#241a00",
        "surface-container-low": "#f4f3f7",
        "on-tertiary-fixed-variant": "#454748",
        "on-background": "#1a1b1e",
        "on-secondary-container": "#745c00",
        "inverse-surface": "#2f3033",
        "primary-fixed-dim": "#aec7f6",
        "inverse-primary": "#aec7f6",
        "secondary-fixed-dim": "#e9c349",
        "surface-tint": "#465f88",
        "surface-variant": "#e3e2e6",
        "error-container": "#ffdad6",
        "background": "#faf9fd",
        "on-primary": "#ffffff",
        "surface": "#faf9fd",
        "secondary": "#735c00",
        "secondary-fixed": "#ffe088",
        "on-primary-fixed": "#001b3d",
        "inverse-on-surface": "#f1f0f4",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-container": "#87898a",
        "surface-bright": "#faf9fd",
        "outline": "#74777f",
        "surface-container-high": "#e9e7eb",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed65b",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container": "#efedf1",
        "tertiary-fixed-dim": "#c5c7c8",
        "tertiary-fixed": "#e1e3e4",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed": "#d6e3ff",
        "error": "#ba1a1a",
        "surface-dim": "#dad9dd",
        "tertiary-container": "#1f2223"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        heading: ["var(--font-poppins)", "Poppins", "sans-serif"],
        poppins: ["var(--font-poppins)", "Poppins", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      boxShadow: {
        'subtle': '0 1px 3px 0 rgba(0, 33, 71, 0.05), 0 1px 2px 0 rgba(0, 33, 71, 0.03)',
        'card': '0 4px 6px -1px rgba(0, 33, 71, 0.06), 0 2px 4px -1px rgba(0, 33, 71, 0.04)',
        'elevated': '0 10px 25px -3px rgba(0, 33, 71, 0.08), 0 4px 6px -2px rgba(0, 33, 71, 0.03)',
        'gold': '0 4px 14px 0 rgba(254, 214, 91, 0.4)'
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
